# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pscrud_pb2 as pscrud__pb2


class PscrudStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Register = channel.unary_unary(
        '/grpc.Pscrud/Register',
        request_serializer=pscrud__pb2.AuthRequest.SerializeToString,
        response_deserializer=pscrud__pb2.AuthResponse.FromString,
        )
    self.Login = channel.unary_unary(
        '/grpc.Pscrud/Login',
        request_serializer=pscrud__pb2.AuthRequest.SerializeToString,
        response_deserializer=pscrud__pb2.AuthResponse.FromString,
        )
    self.Authenticate = channel.unary_unary(
        '/grpc.Pscrud/Authenticate',
        request_serializer=pscrud__pb2.Request.SerializeToString,
        response_deserializer=pscrud__pb2.AuthResponse.FromString,
        )
    self.Logout = channel.unary_unary(
        '/grpc.Pscrud/Logout',
        request_serializer=pscrud__pb2.Request.SerializeToString,
        response_deserializer=pscrud__pb2.Response.FromString,
        )
    self.Deregister = channel.unary_unary(
        '/grpc.Pscrud/Deregister',
        request_serializer=pscrud__pb2.Request.SerializeToString,
        response_deserializer=pscrud__pb2.Response.FromString,
        )
    self.Create = channel.unary_unary(
        '/grpc.Pscrud/Create',
        request_serializer=pscrud__pb2.PutRequest.SerializeToString,
        response_deserializer=pscrud__pb2.PutResponse.FromString,
        )
    self.Read = channel.unary_unary(
        '/grpc.Pscrud/Read',
        request_serializer=pscrud__pb2.GetRequest.SerializeToString,
        response_deserializer=pscrud__pb2.GetResponse.FromString,
        )
    self.Update = channel.unary_unary(
        '/grpc.Pscrud/Update',
        request_serializer=pscrud__pb2.PutRequest.SerializeToString,
        response_deserializer=pscrud__pb2.PutResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/grpc.Pscrud/Delete',
        request_serializer=pscrud__pb2.GetRequest.SerializeToString,
        response_deserializer=pscrud__pb2.Response.FromString,
        )
    self.Subscribe = channel.unary_unary(
        '/grpc.Pscrud/Subscribe',
        request_serializer=pscrud__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=pscrud__pb2.Response.FromString,
        )
    self.Unsubscribe = channel.unary_unary(
        '/grpc.Pscrud/Unsubscribe',
        request_serializer=pscrud__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=pscrud__pb2.Response.FromString,
        )
    self.Publish = channel.unary_unary(
        '/grpc.Pscrud/Publish',
        request_serializer=pscrud__pb2.PublishRequest.SerializeToString,
        response_deserializer=pscrud__pb2.Response.FromString,
        )
    self.Listen = channel.unary_stream(
        '/grpc.Pscrud/Listen',
        request_serializer=pscrud__pb2.Request.SerializeToString,
        response_deserializer=pscrud__pb2.Publication.FromString,
        )


class PscrudServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Authenticate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Logout(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Deregister(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Read(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Unsubscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Publish(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Listen(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PscrudServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Register': grpc.unary_unary_rpc_method_handler(
          servicer.Register,
          request_deserializer=pscrud__pb2.AuthRequest.FromString,
          response_serializer=pscrud__pb2.AuthResponse.SerializeToString,
      ),
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=pscrud__pb2.AuthRequest.FromString,
          response_serializer=pscrud__pb2.AuthResponse.SerializeToString,
      ),
      'Authenticate': grpc.unary_unary_rpc_method_handler(
          servicer.Authenticate,
          request_deserializer=pscrud__pb2.Request.FromString,
          response_serializer=pscrud__pb2.AuthResponse.SerializeToString,
      ),
      'Logout': grpc.unary_unary_rpc_method_handler(
          servicer.Logout,
          request_deserializer=pscrud__pb2.Request.FromString,
          response_serializer=pscrud__pb2.Response.SerializeToString,
      ),
      'Deregister': grpc.unary_unary_rpc_method_handler(
          servicer.Deregister,
          request_deserializer=pscrud__pb2.Request.FromString,
          response_serializer=pscrud__pb2.Response.SerializeToString,
      ),
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=pscrud__pb2.PutRequest.FromString,
          response_serializer=pscrud__pb2.PutResponse.SerializeToString,
      ),
      'Read': grpc.unary_unary_rpc_method_handler(
          servicer.Read,
          request_deserializer=pscrud__pb2.GetRequest.FromString,
          response_serializer=pscrud__pb2.GetResponse.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=pscrud__pb2.PutRequest.FromString,
          response_serializer=pscrud__pb2.PutResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=pscrud__pb2.GetRequest.FromString,
          response_serializer=pscrud__pb2.Response.SerializeToString,
      ),
      'Subscribe': grpc.unary_unary_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=pscrud__pb2.SubscribeRequest.FromString,
          response_serializer=pscrud__pb2.Response.SerializeToString,
      ),
      'Unsubscribe': grpc.unary_unary_rpc_method_handler(
          servicer.Unsubscribe,
          request_deserializer=pscrud__pb2.SubscribeRequest.FromString,
          response_serializer=pscrud__pb2.Response.SerializeToString,
      ),
      'Publish': grpc.unary_unary_rpc_method_handler(
          servicer.Publish,
          request_deserializer=pscrud__pb2.PublishRequest.FromString,
          response_serializer=pscrud__pb2.Response.SerializeToString,
      ),
      'Listen': grpc.unary_stream_rpc_method_handler(
          servicer.Listen,
          request_deserializer=pscrud__pb2.Request.FromString,
          response_serializer=pscrud__pb2.Publication.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc.Pscrud', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
