# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClearKeep' do
  
  pod 'Tink'
  pod 'SwiftyJSON'
  # pod 'SignalServiceKit', git: 'https://github.com/WhisperSystems/SignalServiceKit.git'
  # Pods for ClearKeep

  target 'ClearKeepTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClearKeepUITests' do
    # Pods for testing
  end

end
