# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClearKeep' do
  pod 'Tink', '1.4.0'

  # Pods for ClearKeep

  target 'ClearKeepTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClearKeepUITests' do
    # Pods for testing
  end

end
